=== dokyung-kang/Univ/Web-Service/HW2/XMLExamples/BookML2.0/bookML.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.example.org/bookML"
	xmlns:tns="http://www.example.org/bookML"
	elementFormDefault="qualified">

    <include schemaLocation="bookTypes.xsd"></include>

	<element name="bookCatalog">
		<complexType>
			<annotation>
				<documentation>루트 엘리먼트인 bookCatalog</documentation>	  <!-- annotation 사용 -->
			</annotation>
			<sequence>
				<element ref="tns:bookList"></element>
				<element ref="tns:bookCategory"></element>
			</sequence>
		</complexType>
		<key name="keyIsbn"> 	<!-- 도서 isbn 식별자 key 조건 -->
			<selector xpath="./tns:bookList/tns:book"></selector>
			<field xpath="./@isbn"></field>
		</key>
		<keyref name="keyrefCategory" refer="tns:keyCategory">	<!-- 도서의 분야에 대한 참조무결성 제약 -->
			<selector xpath="./tns:bookList/tns:book/tns:category"></selector>
			<field xpath="."></field>
		</keyref>
	</element>
	
	<element name="bookCategory">	<!-- 분류체계 전역 엘리먼트 -->
		<complexType>
			<sequence>
				<element name="category" type="tns:categoryType" minOccurs="0" maxOccurs="unbounded"></element>
			</sequence>
		</complexType>
		<key name="keyCategory"> <!-- 도서의 분야에 대한 제약 조건 -->
			<selector xpath=".//tns:category"></selector>
			<field xpath="./@cid"></field>
		</key>
	</element>
	
	<element name="bookList">	<!-- 도서 목록 전역 엘리먼트 -->
		<complexType>
			<sequence>
				<element name="book" type="tns:bookType" minOccurs="0" maxOccurs="unbounded"></element>
			</sequence>
		</complexType>
	</element>
	
	<element name="publishDate">	<!-- 출판일 전역 엘리먼트 -->
		<complexType>
			<attributeGroup ref="tns:dateGroup"></attributeGroup>
		</complexType>
	</element>
	
	<element name="revisionDate">	<!-- 개정일 전역 엘리먼트 -->
		<complexType>
			<attributeGroup ref="tns:dateGroup"></attributeGroup>
		</complexType>
	</element>

	<complexType name="categoryType">	<!-- bookCategory 타입 -->
		<sequence>
			<element name="category" type="tns:categoryType" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="cid" type="string"></attribute>
		<attribute name="name" type="string"></attribute>
	</complexType>

	<complexType name="bookType">	<!-- 일반 도서 타입 -->
		<sequence>
			<element name="title" type="string"/>
			<element name="originalTitle" type="string" minOccurs="0" maxOccurs="1"></element>
			<element name="author" type="string" minOccurs="1" maxOccurs="unbounded"></element>
			<element name="translator" type="string" minOccurs="0" maxOccurs="1"></element>
			<element name="publisher" type="string"></element>
			<element ref="tns:publishDate" minOccurs="0" maxOccurs="unbounded"></element>
			<element ref="tns:revisionDate" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="price" type="tns:priceType"></element>
			<element name="pages" type="tns:pagesType"></element>
			<element name="avgScore" type="tns:avgType"></element>
			<element name="discountRate" type="tns:discountType"  minOccurs="0" maxOccurs="unbounded"></element>
			<element name="coverImage" type="tns:coverImage" minOccurs="0" maxOccurs="1"></element>
			<element name="category" type="string" minOccurs="0" maxOccurs="unbounded"></element>
			<element name="description" type="string" minOccurs="0" maxOccurs="1"></element>
			<element name="review" type="string" minOccurs="0" maxOccurs="unbounded"></element>
		</sequence>
		<attribute name="isbn" type="tns:isbnType"></attribute>
	</complexType>

	<complexType name="eBookType">	<!-- 전자 도서 타입 -->
		<complexContent>
			<extension base="tns:bookType">
				<sequence>	<!-- 전자 도서 추가 정보 -->
					<element name="format" type="tns:fileFormatType"></element>
					<element name="size" type="tns:fileSizeType"></element>
					<element name="period" type="positiveInteger" minOccurs="0" maxOccurs="1"></element>
				</sequence>
			</extension>
		</complexContent>
	</complexType>

	<complexType name="newEBookType">	<!-- 신간 전자 도서 타입 -->
		<complexContent>
			<restriction base="tns:eBookType">	<!-- 재선언 -->
				<sequence>
					<element name="title" type="string"></element>
					<element name="originalTitle" type="string" minOccurs="0" maxOccurs="1"></element>
					<element name="author" type="string" minOccurs="1" maxOccurs="unbounded"></element>
					<element name="translator" type="string" minOccurs="0" maxOccurs="1"></element>
					<element name="publisher" type="string"></element>
					<element ref="tns:publishDate" minOccurs="0" maxOccurs="unbounded"></element>
					<element ref="tns:revisionDate" minOccurs="0" maxOccurs="0"></element>
					<element name="price" type="tns:priceType"></element>
					<element name="pages" type="tns:pagesType"></element>
					<element name="avgScore">	<!-- 평점 제한 -->
						<simpleType>
							<restriction base="tns:avgType">
								<minInclusive value="2"></minInclusive>
								<maxInclusive value="8"></maxInclusive>
							</restriction>
						</simpleType>
					</element>
					<element name="discountRate">	<!-- 할인률 제한 -->
						<simpleType>
							<restriction base="tns:discountType">
								<minInclusive value="0"></minInclusive>
								<maxInclusive value="10"></maxInclusive>
							</restriction>
						</simpleType>
					</element>
					<element name="coverImage" type="tns:coverImage" minOccurs="0" maxOccurs="1"></element>
					<element name="category" type="string" minOccurs="0" maxOccurs="unbounded"></element>
					<element name="description" type="string" minOccurs="0" maxOccurs="1"></element>
					<element name="review" type="string"  minOccurs="0" maxOccurs="unbounded"></element>
					<element name="format" type="tns:fileFormatType"></element>
					<element name="size" type="tns:fileSizeType"></element>
					<element name="period">	<!-- 기간 제한 -->
						<simpleType>
							<restriction base="positiveInteger">
								<maxInclusive value="14"></maxInclusive>
							</restriction>
						</simpleType>
					</element>
				</sequence>
			</restriction>
		</complexContent>
	</complexType>
	
</schema>

=== dokyung-kang/Univ/Web-Service/HW2/XMLExamples/BookML2.0/bookML.xml
<?xml version="1.0" encoding="UTF-8"?>
<bookCatalog
	xmlns="http://www.example.org/bookML"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.example.org/bookML bookML.xsd ">
	<bookList>
		<book isbn="895467277-9" xsi:type="bookType">
			<title>일곱해의 마지막</title>
			<author>김연수</author>
			<publisher>문학동네</publisher>
			<publishDate year="2020" month="07" day="01"/>
			<revisionDate year="2021" month="02" day="15"/>
			<price currency="won">
				<listPrice>13500</listPrice>
				<discountPrice>12150</discountPrice>
			</price>
			<pages>248</pages>
			<avgScore>8.5</avgScore>
			<coverImage src="http://image.yes24.com/goods/90619474/L" type="jpeg"></coverImage>
			<category>c101-1-1</category>
			<description>
				개인이 밟아나간 작품 활동의 궤적을 곧 한국소설의 중요한 흐름 가운데 하나
				로 만들어내며 한국문학의 판도를 뒤바꾼 작가 김연수의 신작 장편소설. 삼십 년 가까이 작가생활을 하는 동
				안 김연수는 에너지와 불안으로 가득한 청춘의 눈빛을 가장 가까이에서 기록하는 한편으로 사랑의 본질에 대
				해 끊임없이 탐구하며 그만의 지적인 사랑학 개론을 펼쳐왔다. 그리고 그와 동시에 방대한 역사적 자료를 바
				탕으로 객관적인 사실로는 가닿을 수 없는 빈틈에서 개인의 진실을 발견해내는 작업을 해오기도 했다.
			</description>
			<review>
				김연수 작가님의 오랜만의 신작이라 구매했어요. 일제강점기 이후 해방과 전쟁, 분단
				등 혼란한 시기 북으로 간 시인 백석의 이야기입니다. 전쟁이 끝난 7년 동안의 백석의 이야기. 작가님도 8년
				만의 신작인데 그 시간동안 백석의 시간을 곱씹어 보셨을까요. 책의 대한 정보 하나도 없이 작가님 이름만 보
				고 구입했는데 제목이 직관적이었네요. 마음이 많이 무거워지고 여운도 많이 남는 글이었습니다.
			</review>
			<review>
				좋았다
			</review>
		</book>
		<book isbn="895467277-8" xsi:type="eBookType">
			<title>사피엔스</title>
			<originalTitle>Sapiens: A Brief History of Humankind</originalTitle>
			<author>유발 하라리</author>
			<translator>조현욱</translator>
			<publisher>김영사</publisher>
			<price currency="won">
				<listPrice>12000</listPrice>
				<discountPrice>10800</discountPrice>
			</price>
			<pages>241</pages>
			<avgScore>9.5</avgScore>
			<category>c101-1</category>
			<category>c103-2</category>
			<description>
				변방의 유인원 호모 사피엔스는 어떻게 세상의 지배자가 되었는가? 수렵채집을
				하던 우리 조상들은 어떻게 한 곳에 모여 도시와 왕국을 건설하였는가? 인간은 왜 지구 역사상 가장 치명적인
				동물이 되었는가? 과학은 모든 종교의 미래인가? 인간의 유효기간은 언제까지인가? 멀고먼 인류의 시원부터
				인지혁명, 농업혁명, 과학혁명을 거쳐 끊임없이 진화해온 인간의 역사를 생물학, 경제학, 종교학, 심리학, 철학
				등 여러 학문의 경계를 넘나들며 다양하고 생생하게 조명한 전인미답의 문제작. 호모 사피엔스부터 인공지능
				까지, 기나긴 역사의 시간을 한 권으로 써내려간 문명 항해기. 이제 우리는 무엇을 인간이라고 할 것인가.
			</description>
			<format value="EPUB"></format>
			<size unit="MB">26.60</size>
			<period>30</period>
		</book>
		<book isbn="895467277-7" xsi:type="newEBookType">
			<title>인간 불평등 기원론</title>
			<author>장 자크 루소</author>
			<publisher>아무개</publisher>
			<publishDate year="2021" month="01" day="25"/>
			<price currency="won">
				<listPrice>13000</listPrice>
				<discountPrice>12900</discountPrice>
			</price>
			<pages>300</pages>
			<avgScore>6.8</avgScore>
			<discountRate>10</discountRate>
			<category>c102-1</category>
			<format value="EPUB"></format>
			<size unit="GB">13.21</size>
			<period>10</period>
		</book>
	</bookList>
	<bookCategory>
		<category cid="c101" name="문학">
			<category cid="c101-1" name="소설">
				<category cid="c101-1-1" name="한국소설"></category>
				<category cid="c101-1-2" name="영미소설"></category>
			</category>
			<category cid="c101-2" name="시"></category>
			<category cid="c101-3" name="희곡"></category>
		</category>
		<category cid="c102" name="인문">
			<category cid="c102-1" name="철학/사상"></category>
			<category cid="c102-2" name="심리학"></category>
		</category>
		<category cid="c103" name="역사">
			<category cid="c103-1" name="한국사"></category>
			<category cid="c103-2" name="세계사"></category>
		</category>
	</bookCategory>
</bookCatalog>
